version: '2'

services: 
  joomladb:
    image: mysql:5.7
    volumes:
     - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: aashi
      MYSQL_PASSWORD: redhat@123
      MYSQL_DATABASE: mydb


  joomlaos:
    image: joomla:3.9-php7.2-apache
    restart: always
    depends_on: 
      - joomladb
    ports: 
      - 80:80
    environment:
      JOOMLA_DB_HOST: joomladb:3306      
      JOOMLA_DB_USER: aashi
      JOOMLA_DB_PASSWORD: redhat@123
      JOOMLA_DB_NAME: mydb
    volumes: 
     - joomla_storage_new:/var/www/html


volumes:
  mysql_storage_new:
  joomla_storage_new:
